/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as GamesImport } from "./routes/games"
import { Route as GamesSlugImport } from "./routes/games.$slug"
import { Route as LeaderboardImport } from "./routes/leaderboard"
import { Route as ProfileImport } from "./routes/profile"
import { Route as NewsImport } from "./routes/news"
import { Route as rootRouteImport } from "./routes/__root"
import { Route as indexImport } from "./routes/index"
import { createFileRoute } from "@tanstack/react-router"

const IndexRoute = indexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

const GamesRoute = GamesImport.update({
  id: "/games",
  path: "/games",
  getParentRoute: () => rootRouteImport,
} as any)

const GamesSlugRoute = GamesSlugImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => GamesRoute,
} as any)

const LeaderboardRoute = LeaderboardImport.update({
  id: "/leaderboard",
  path: "/leaderboard",
  getParentRoute: () => rootRouteImport,
} as any)

const ProfileRoute = ProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)

const NewsRoute = NewsImport.update({
  id: "/news",
  path: "/news",
  getParentRoute: () => rootRouteImport,
} as any)

declare module "@tanstack/react-router" {
  interface FileRouteTypes {
    children: never
    parent: never
    path: "" | "/" | "/games" | "/games/$slug" | "/leaderboard" | "/profile" | "/news"
  }
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

export interface FileRouteTypes {
  children: typeof GamesRouteWithChildren
  parent: typeof rootRouteImport
}

const rootRouteChildren = {
  GamesRoute: GamesRouteWithChildren,
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  NewsRoute: NewsRoute,
}

const GamesRouteChildren = {
  GamesSlugRoute: GamesSlugRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

routeTree.buildRouteTree()
